- name: Deactivate SSL
  when: "not slapd_ssl"
  notify: Restart slapd
  block:
    - name: Configure slapd services without slaps:///
      ansible.builtin.lineinfile:
        path: "/etc/default/slapd"
        regexp: "^SLAPD_SERVICES="
        line: 'SLAPD_SERVICES="ldap:/// ldapi:///"'
    - name: Remove slapd user from SSL group
      when: "not slapd_ssl"
      ansible.builtin.user:
        user: "{{ slapd_user }}"
        groups: []

- name: Activate SSL
  when: "slapd_ssl"
  notify: Restart slapd
  block:
    - name: Configure slapd services with slaps:///
      ansible.builtin.lineinfile:
        path: "/etc/default/slapd"
        regexp: "^SLAPD_SERVICES="
        line: 'SLAPD_SERVICES="ldap:/// ldaps:/// ldapi:///"'
    - name: Add slapd user to SSL group
      when: "slapd_ssl"
      ansible.builtin.user:
        user: "{{ slapd_user }}"
        groups: ["{{ slapd_ssl_group }}"]
