- name: Search for all suffixes
  community.general.ldap_search:
    dn: "cn=config"
    filter: "(&(objectClass=olcDatabaseConfig)(olcSuffix=*))"
    scope: "children"
    attrs: ["olcSuffix", "olcDbDirectory"]
  ignore_errors: true
  register: out_existing_suffixes

- name: Delete backend
  loop: "{{ out_existing_suffixes.results }}"
  when: "item.olcSuffix not in wanted_suffixes"
  community.general.ldap_entry:
    dn: "{{ item.dn }}"
    state: "absent"

- name: Delete backend directory
  loop: "{{ out_existing_suffixes.results }}"
  when: "item.olcSuffix not in wanted_suffixes"
  ansible.builtin.file:
    path: "{{ item.olcDbDirectory }}"
    state: "absent"

- name: Stat apparmor file
  ansible.builtin.stat:
    path: "{{ slapd_apparmor_file }}"
  register: out_apparmor_file

- name: Configure apparmor - directory {{ item.olcDbDirectory }}
  loop: "{{ out_existing_suffixes.results }}"
  when: "item.olcSuffix not in wanted_suffixes and out_apparmor_file.stat.exists"
  ansible.builtin.lineinfile:
    path: "{{ slapd_apparmor_file }}"
    regexp: "{{ item.olcDbDirectory }}\\/\\s+r,"
    state: "absent"

- name: Configure apparmor - content for directory {{ item.olcDbDirectory }}
  loop: "{{ out_existing_suffixes.results }}"
  when: "item.olcSuffix not in wanted_suffixes and out_apparmor_file.stat.exists"
  ansible.builtin.lineinfile:
    path: "{{ slapd_apparmor_file }}"
    regexp: "{{ item.olcDbDirectory }}\\/\\*\\*\\s+rwk,"
    state: "absent"
