---
- name: Install slapd
  ansible.builtin.include_tasks: "install-slapd.yml"

- name: Configure SSL
  ansible.builtin.include_tasks: "configure-ssl.yml"

- name: Configure monitor backend
  ansible.builtin.include_tasks: "configure-monitor.yml"

- name: Add schemas
  ansible.builtin.include_tasks: "add-schemas.yml"

- name: Add modules
  ansible.builtin.include_tasks: "add-modules.yml"

- name: Configuration - Root OLC
  community.general.ldap_attrs:
    dn: "cn=config"
    attributes: "{{ slapd_config_olc }}"
    state: "exact"

- name: Configuration - frontend
  community.general.ldap_attrs:
    dn: "olcDatabase={-1}frontend,cn=config"
    attributes: "{{ slapd_config_frontend }}"
    state: "exact"

- name: Configuration - config
  community.general.ldap_attrs:
    dn: "olcDatabase={0}config,cn=config"
    attributes: "{{ slapd_config_config }}"
    state: "exact"

- name: Delete backends
  vars:
    wanted_suffixes: "{{ slapd_config_backends | map(attribute='attributes.olcSuffix') }}"
  ansible.builtin.include_tasks: "delete-backends.yml"

- name: Backends creation/configuration
  loop: "{{ slapd_config_backends }}"
  vars:
    suffix: "{{ item.attributes.olcSuffix | mandatory }}"
    db_type: "{{ item.db_type | mandatory }}"
    attributes: "{{ item.attributes }}"
    dit: "{{ item.dit | default({}) }}"
  ansible.builtin.include_tasks: "configure-backend.yml"

- name: Delete overlays
  loop: "{{ slapd_config_backends }}"
  vars:
    suffix: "{{ item.attributes.olcSuffix }}"
    wanted_overlays: "{{ item.overlays | default([]) | map(attribute='name') }}"
  ansible.builtin.include_tasks: "delete-overlays.yml"

- name: Overlays creation/configuration
  loop: "{{ slapd_config_backends | subelements('overlays', skip_missing='True') }}"
  vars:
    suffix: "{{ item.0.attributes.olcSuffix }}"
    overlay: "{{ item.1 }}"
  ansible.builtin.include_tasks: "configure-overlay.yml"
