---
- name: Install pre-required packages
  ansible.builtin.apt:
    name:
      - "debconf-utils"
      - "ssl-cert"

# This backend will be deleted by "Delete backends" task
- name: Pre-configure slapd dummy.domain.to.delete with debconf
  ansible.builtin.debconf:
    name: "slapd"
    question: "slapd/domain"
    value: "dummy.domain.to.delete"
    vtype: "string"

- name: Install required packages
  ansible.builtin.apt:
    name:
      - "slapd"
      - "schema2ldif"
      - "python3-ldap"

- name: Configure SSL
  ansible.builtin.include_tasks: "configure-ssl.yml"

- name: Add schemas
  ansible.builtin.include_tasks: "add-schemas.yml"

- name: Add modules
  ansible.builtin.include_tasks: "add-modules.yml"

- name: Root OLC configuration
  community.general.ldap_attrs:
    dn: "cn=config"
    attributes: "{{ slapd_config_olc }}"
    state: "exact"

- name: Configuration - frontend
  community.general.ldap_attrs:
    dn: "olcDatabase={-1}frontend,cn=config"
    attributes: "{{ slapd_config_frontend }}"
    state: "exact"

- name: Configuration - config
  community.general.ldap_attrs:
    dn: "olcDatabase={0}config,cn=config"
    attributes: "{{ slapd_config_config }}"
    state: "exact"

- name: Backends creation/configuration
  loop: "{{ slapd_config_backends }}"
  vars:
    suffix: "{{ item.attributes.olcSuffix | mandatory }}"
    db_type: "{{ item.db_type | mandatory }}"
    attributes: "{{ item.attributes }}"
  ansible.builtin.include_tasks: "configure-backend.yml"

- name: Delete backends
  vars:
    wanted_suffixes: "{{ slapd_config_backends | map(attribute='attributes.olcSuffix') }}"
  ansible.builtin.include_tasks: "delete-backends.yml"
