---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    slapd_rootdn: "dc=test,dc=me"
    slapd_admin_dn: "cn=admin,dc=test,dc=me"
    slapd_admin_pw: "abc123"
  become: true
  tasks:
    - name: Include role slapd
      ansible.builtin.include_role:
        name: "slapd"
