---
driver:
  name: molecule_multipass

dependency:
  name: "galaxy"
  options:
    requirements-file: "requirements.yml"

lint: >
  set -e
  yamllint .
  ansible-lint .

platforms:
  - name: "jammy"
    vm_image: "22.04"

provisioner:
  name: ansible

verifier:
  name: ansible
