- name: Verify
  hosts: all
  gather_facts: true

  tasks:

  - name: Collect packages as facts
    ansible.builtin.package_facts:
 
  - name: Collect services as facts
    ansible.builtin.service_facts:

  - name: Debug1
    ansible.builtin.debug:
      var: ansible_facts

  - name: Check slapd installed and running
    ansible.builtin.assert:
      that:
        - "'slapd' in ansible_facts.packages"
        - "ansible_facts.services['slapd.service'].state == 'running'"
