- name: Verify
  hosts: all
  gather_facts: true

  tasks:
  
  - name: Collect packages as facts
    package_facts:
 
  - name: Collect services as facts
    service_facts:
 
  - name: Collect ports as facts
    listen_ports_facts:

  - name: Debug1
    ansible.builtin.debug:
      var: ansible_facts

  - name: Check slapd installed and running
    assert:
      that:
      - "'slapd' in ansible_facts.packages"
      - "ansible_facts.services['slapd.service'].state == 'running'"
      - "389 in ansible_facts.tcp_listen | map(attribute='port')"
